/* Generated By:JavaCC: Do not edit this line. parserTreeConstants.java Version 5.0 */
package parser;

public interface parserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTPROGRAM = 1;
  public int JJTTYPE = 2;
  public int JJTSTATEMENTBLOCK = 3;
  public int JJTSTATEMENT = 4;
  public int JJTSEQSTATEMENT = 5;
  public int JJTDECSTATEMENT = 6;
  public int JJTCDLSTATEMENT = 7;
  public int JJTIFSTATEMENT = 8;
  public int JJTSWITCHSTATEMENT = 9;
  public int JJTLOOPSTATEMENT = 10;
  public int JJTFORSTATEMENT = 11;
  public int JJTWHILESTATEMENT = 12;
  public int JJTDOWHILESTATEMENT = 13;
  public int JJTBOOL = 14;
  public int JJTANDBOOL = 15;
  public int JJTCONDITION = 16;
  public int JJTEXPRESSION = 17;
  public int JJTADDITIVEEXPRESSION = 18;
  public int JJTMULTIPLICATIVEEXPRESSION = 19;
  public int JJTUNARYEXPRESSION = 20;
  public int JJTIDENTIFIER = 21;
  public int JJTINTEGER = 22;


  public String[] jjtNodeName = {
    "Start",
    "Program",
    "type",
    "StatementBlock",
    "statement",
    "seqStatement",
    "decStatement",
    "cdlStatement",
    "ifStatement",
    "switchStatement",
    "loopStatement",
    "forStatement",
    "whileStatement",
    "dowhileStatement",
    "bool",
    "andBool",
    "Condition",
    "Expression",
    "AdditiveExpression",
    "MultiplicativeExpression",
    "UnaryExpression",
    "Identifier",
    "Integer",
  };
}
/* JavaCC - OriginalChecksum=249b313ce8a4c0ac3860fd6f3fd9da36 (do not edit this line) */
