/* Generated By:JJTree&JavaCC: Do not edit this line. parserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONSTANT = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int INTEGER = 9;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 10;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 11;
  /** RegularExpression Id. */
  int HEX_LITERAL = 12;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 13;
  /** RegularExpression Id. */
  int MAIN = 14;
  /** RegularExpression Id. */
  int VOID = 15;
  /** RegularExpression Id. */
  int INT = 16;
  /** RegularExpression Id. */
  int FLOAT = 17;
  /** RegularExpression Id. */
  int CHAR = 18;
  /** RegularExpression Id. */
  int DOUBLE = 19;
  /** RegularExpression Id. */
  int IF = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int SWITCH = 24;
  /** RegularExpression Id. */
  int CASE = 25;
  /** RegularExpression Id. */
  int BREAK = 26;
  /** RegularExpression Id. */
  int Default = 27;
  /** RegularExpression Id. */
  int FOR = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int PLUS = 30;
  /** RegularExpression Id. */
  int MINUS = 31;
  /** RegularExpression Id. */
  int MULTIPLY = 32;
  /** RegularExpression Id. */
  int DIVIDE = 33;
  /** RegularExpression Id. */
  int EQUAL = 34;
  /** RegularExpression Id. */
  int ZIZENG = 35;
  /** RegularExpression Id. */
  int ZIJIAN = 36;
  /** RegularExpression Id. */
  int LT = 37;
  /** RegularExpression Id. */
  int LE = 38;
  /** RegularExpression Id. */
  int GT = 39;
  /** RegularExpression Id. */
  int GE = 40;
  /** RegularExpression Id. */
  int EQ = 41;
  /** RegularExpression Id. */
  int NE = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int AND = 44;
  /** RegularExpression Id. */
  int IDENTIFIER = 45;
  /** RegularExpression Id. */
  int LETTER = 46;
  /** RegularExpression Id. */
  int STRING = 47;
  /** RegularExpression Id. */
  int LP = 48;
  /** RegularExpression Id. */
  int RP = 49;
  /** RegularExpression Id. */
  int LM = 50;
  /** RegularExpression Id. */
  int RM = 51;
  /** RegularExpression Id. */
  int LB = 52;
  /** RegularExpression Id. */
  int RB = 53;
  /** RegularExpression Id. */
  int COMMA = 54;
  /** RegularExpression Id. */
  int COLON = 55;
  /** RegularExpression Id. */
  int DANYIN = 56;
  /** RegularExpression Id. */
  int SHUANGYIN = 57;
  /** RegularExpression Id. */
  int DOT = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<CONSTANT>",
    "<DIGIT>",
    "<INTEGER>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"main\"",
    "\"void\"",
    "\"int\"",
    "\"float\"",
    "\"char\"",
    "\"double\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"switch\"",
    "\"case\"",
    "\"break\"",
    "\"default\"",
    "\"for\"",
    "\"return\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\"=>\"",
    "\"==\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<STRING>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\":\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "\".\"",
    "\";\"",
    "\"%\"",
  };

}
